### ISSUE TITLE
Add a more user-friendly message when a session is not found

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/go.resonite.com#2]
It would be nice to have a better 404 message when a session cannot be found.

Right now, it displays:
```
NotFoundError: Couldn't find session
    at createResoniteApiError (/usr/src/app/routes/index.js:26:12)
    at handle (/usr/src/app/routes/index.js:36:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

Which can be interpreted as an error by users, I think a text like:
```
Whoops, this session cannot be found.
Check that the link is valid, that the session didn't end or that the session is visible publicly.
```
Would do better.

**Comment by ProbablePrime** [comment]
Updated! 

Thank you: https://github.com/Yellow-Dog-Man/go.resonite.com/blob/main/routes/index.js#L26
